// Statically imported (rather than read via `fs` at render time) so Next
// bundles it into the server output. A runtime `fs.readFileSync` of a computed
// path isn't picked up by Next's file tracing, so it's dropped from the
// production build and the import map silently disappears - which breaks the
// fiddles' `import('@fantoche/2d')` with "bare specifier ... not remapped".
//
// The manifest is generated by scripts/copy-modules.mjs, which runs before
// `next build`/`next dev` (see package.json). It maps `@fantoche/core` /
// `@fantoche/2d` to the hashed ESM bundles copied into public/modules.
import manifest from '@/generated/modules.json';

// Keep in sync with `basePath` in next.config.ts.
const BASE_PATH = '/revideo';

/**
 * Injects the import map that lets the interactive fiddles resolve
 * `import('@fantoche/core')` / `import('@fantoche/2d')` at runtime to the ESM
 * bundles copied into public/modules by scripts/copy-modules.mjs.
 */
export function RevideoImportMap() {
  const importMap = {
    imports: {
      '@fantoche/core': `${BASE_PATH}${manifest['@fantoche/core']}`,
      '@fantoche/2d': `${BASE_PATH}${manifest['@fantoche/2d']}`,
      '@fantoche/2d/jsx-runtime': `${BASE_PATH}${manifest['@fantoche/2d']}`,
      '@lezer/javascript': 'https://esm.sh/@lezer/javascript',
    },
  };

  return (
    <script
      type="importmap"
      dangerouslySetInnerHTML={{__html: JSON.stringify(importMap)}}
    />
  );
}
