import {renderVideo} from '@fantoche-dev/renderer';
import * as crypto from 'crypto';
import * as fs from 'fs';
import * as path from 'path';

export interface RenderDocOptions {
  out?: string;
  outDir?: string;
  workers?: string;
}

/**
 * Generate the shim project module for a document.
 *
 * The shim must live INSIDE the workspace (vite fs.allow) and be handed to
 * renderVideo as a cwd-relative path; the document is inlined as a literal
 * (no JSON resolution issues) and block sources are imported statically so
 * vite can bundle them. Exported for testing.
 */
export function generateShim(
  document: unknown,
  name: string,
  blockSrcs: {src: string; exportName: string}[],
  docDir: string,
  shimDir: string,
): string {
  const imports: string[] = [
    `import {makeDocumentProject} from '@fantoche-dev/document/scene';`,
  ];
  const entries: string[] = [];
  blockSrcs.forEach((block, i) => {
    const resolved = path.resolve(docDir, block.src);
    let relative = path.relative(shimDir, resolved).split(path.sep).join('/');
    if (!relative.startsWith('.')) {
      relative = `./${relative}`;
    }
    imports.push(`import * as block${i} from '${relative}';`);
    entries.push(
      `  '${block.src}#${block.exportName}': block${i}['${block.exportName}'],`,
    );
  });
  return [
    '// Generated by `fantoche render` — safe to delete.',
    ...imports,
    '',
    `const doc = ${JSON.stringify(document, null, 2)} as const;`,
    '',
    `export default makeDocumentProject(doc, ${JSON.stringify(name)}, {`,
    '  blocks: {',
    ...entries,
    '  },',
    '});',
    '',
  ].join('\n');
}

export async function renderDoc(
  docPath: string,
  options: RenderDocOptions,
): Promise<void> {
  const {validateDocument, migrateDocument, MigrationError} = await import(
    '@fantoche-dev/document'
  );

  const resolvedDocPath = path.resolve(docPath);
  let raw: unknown;
  try {
    raw = JSON.parse(fs.readFileSync(resolvedDocPath, 'utf8'));
  } catch (error) {
    console.error(`Could not read document: ${(error as Error).message}`);
    process.exit(1);
  }

  let migrated;
  try {
    migrated = migrateDocument(raw);
  } catch (error) {
    if (error instanceof MigrationError) {
      console.error(error.message);
      process.exit(1);
    }
    throw error;
  }
  if (migrated.applied.length > 0) {
    console.log(`Migrated document: ${migrated.applied.join(', ')}`);
  }

  const validation = validateDocument(migrated.doc);
  if (!validation.ok) {
    console.error('Invalid document:');
    for (const issue of validation.errors) {
      console.error(`  ${issue.path}: ${issue.message}`);
    }
    process.exit(1);
  }

  const name = path.basename(docPath).replace(/\.json$/i, '');
  const outFile = options.out ?? `${name}.mp4`;
  if (!outFile.endsWith('.mp4')) {
    console.error(`--out must end in .mp4 (got "${outFile}")`);
    process.exit(1);
  }

  const blockSrcs = (
    validation.doc.timeline as Array<Record<string, unknown>>
  ).flatMap(item => {
    if (typeof item.block !== 'object' || item.block === null) {
      return [];
    }
    const src = (item.block as {src: string}).src;
    const hash = src.lastIndexOf('#');
    return [{src: src.slice(0, hash), exportName: src.slice(hash + 1)}];
  });

  const shimDir = path.join(process.cwd(), 'node_modules', '.fantoche');
  fs.mkdirSync(shimDir, {recursive: true});
  const shimSource = generateShim(
    validation.doc,
    name,
    blockSrcs,
    path.dirname(resolvedDocPath),
    shimDir,
  );
  const shimName = `render-${crypto
    .createHash('sha1')
    .update(shimSource)
    .digest('hex')
    .slice(0, 12)}.ts`;
  const shimPath = path.join(shimDir, shimName);
  fs.writeFileSync(shimPath, shimSource);

  try {
    const file = await renderVideo({
      projectFile: `./node_modules/.fantoche/${shimName}`,
      settings: {
        outFile: outFile as `${string}.mp4`,
        outDir: options.outDir ?? './output',
        workers:
          options.workers === undefined
            ? undefined
            : Number.parseInt(options.workers, 10),
        logProgress: true,
        projectSettings: {
          exporter: {name: '@fantoche-dev/core/wasm'},
        },
      },
    });
    console.log(`Rendered video to ${file}`);
  } finally {
    fs.unlinkSync(shimPath);
  }
}
